version: '3.1'

services:

  db:
    image: postgres:10
    container_name: "appdb"
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: test01
      POSTGRES_PASSWORD: test01test01
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
